name: Release Branch Automation
on:
  push:
    branches:
      - main
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "KiranBkittu"
          git config user.email "kiran.bandi786@gmail.com"

      - name: Prepare release branch
        run: |
          RELEASE_BRANCH="release-${GITHUB_SHA::7}"
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
          git fetch origin

          if git ls-remote --exit-code --heads origin $RELEASE_BRANCH; then
            echo "Branch exists â†’ checkout"
            git checkout $RELEASE_BRANCH
          else
            echo "Creating new branch"
            git checkout -b $RELEASE_BRANCH
          fi

      - name: Make guaranteed change
        run: |
          echo "Build: $GITHUB_RUN_ID" >> file1.txt
          git add file1.txt
          git commit -m "Update file to create diff" || echo "No change"

      - name: Push branch
        run: |
          git push origin $RELEASE_BRANCH --force

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.RELEASE_BRANCH }}
          title: "Release PR ${{ env.RELEASE_BRANCH }}"